version: '3'
services:
  db:
    image: mysql:latest
    container_name: 'cake4_db'
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_DATABASE: cake4_db
      MYSQL_USER: cake4_db
      MYSQL_PASSWORD: cake4_db
      MYSQL_ROOT_PASSWORD: 7fmbnt22
    volumes:
      - ./mysql/data:/var/lib/mysql
    expose:
      - 3306
  php-fpm:
    build: ./phpfpm/
    container_name: 'cake4_phpfpm'
    volumes:
      - /usr/workspaces/d.cake4.vm:/var/www
    privileged: true
    depends_on:
      - 'db'
  web:
    image: nginx:latest
    container_name: 'cake4_web'
    environment:
      VIRTUAL_HOST: d.cake4.vm
    volumes:
      - /usr/workspaces/d.cake4.vm:/usr/share/nginx
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    privileged: true
    expose:
      - 80
    depends_on:
      - 'php-fpm'
networks:
  default:
    external:
      name: common_link
